# Generated by Django 3.2.3 on 2021-05-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210520_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='linkImage',
            new_name='link_Image',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='linkSource',
            new_name='link_Source',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='nameClothes',
            new_name='name_Clothes',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='setOfClothes',
            new_name='set_Of_Clothes',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='typeClothes',
            new_name='type_Clothes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dateCreate',
            new_name='created_at',
        ),
    ]
