# Generated by Django 3.2.3 on 2021-05-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210520_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='setofclothes',
            name='nameSet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
