# Generated by Django 3.2.3 on 2021-05-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_setofclothes_nameset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setofclothes',
            old_name='nameSet',
            new_name='name_Set_Of_Clothes',
        ),
    ]
